#!/usr/bin/env python

import os,sys
import urllib
import platform

LTVERS="LoopTools-2.13"

def main(arg1):
	os.chdir(arg1) 
	print "Fetching LoopTools"
	url="http://www.feynarts.de/looptools/"+LTVERS+".tar.gz"
	urllib.urlretrieve(url, "looptools.tar.gz")
	os.system('tar xzvf looptools.tar.gz')
	os.system('patch ' +  LTVERS +'/src/makefile -i patch_makefile')
	os.chdir(arg1+LTVERS)
	os.system('./configure CFLAGS="-fomit-frame-pointer -fPIC" FFLAGS="-fPIC -ff2c" CXXFLAGS="-fomit-frame-pointer -fPIC" --generic')
	os.system('make')
        fl=os.popen('find '+arg1+ ' -name looptools.so').readlines()
	arch=platform.system()
	if arch == 'Darwin':
		os.system('sed -i \'\' \'s~SHAREDLIBNAME~"'+fl[0].rstrip('\n')+'"~g\' '+ arg1+'/../ltools.py')
	if arch == 'Linux':
		os.system('sed -i  \'s~SHAREDLIBNAME~"'+fl[0].rstrip('\n')+'"~g\' '+ arg1+'/../ltools.py')

if __name__ == "__main__":
	main(sys.argv[1])
